name: Tests

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3]
        laravel: ['10.*', '11.*']
        exclude:
          - laravel: 11.*
            php: 8.1

    name: OS:${{ matrix.os }} / PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_BIN_DIR=$(bun env | grep BUN_BIN_DIR | cut -d'=' -f2 | tr -d '\n')
          export PATH=$BUN_BIN_DIR:$PATH
          echo "Bun setup completed"
          bun --version

      - name: Install Bun Dependencies
        run: bun install

      - name: Run Bun Lint
        run: bun lint

      - name: Bun Build
        run: bun build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Install Composer
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-progress --ansi --no-update
          composer update --no-interaction --no-progress --ansi

      - name: Rector Cache
        uses: actions/cache@v4
        with:
          path: ./var/cache/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Setup Google Chrome
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Pint
        run: ./vendor/bin/pint --test

      - name: Rector
        run: ./vendor/bin/rector process --dry-run --config=rector.php

      - name: PHPStan
        run: ./vendor/bin/phpstan --configuration="phpstan.neon"

      - name: Clear Orchestra Testbench Cache
        run: ./vendor/bin/testbench view:clear

      - name: Feature Tests
        run: ./vendor/bin/pest --ci --filter Feature

      - name: Clear Orchestra Testbench Cache
        run: ./vendor/bin/testbench view:clear

      - name: Browser Tests
        run: ./vendor/bin/pest --ci --filter Browser --order-by random --stop-on-failure
        env:
          CI: true
